# Generated by Django 3.2.8 on 2021-11-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberSis', models.IntegerField(verbose_name='number')),
                ('numberBro', models.IntegerField(verbose_name='number')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('mes', models.CharField(max_length=50, verbose_name='message')),
            ],
        ),
    ]
